apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: smartcheck
  region: us-east-1

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t2.small
    desiredCapacity: 3
    minSize: 3
    maxSize: 4  
    ssh: # use existing EC2 key
      publicKeyName: devops
